
# 定义 stages
stages:
  - build
  - test
  - deploy

# 定义编译阶段
build_stages:
  stage: build
  script:
    - npm install 
    - echo "npm sucess~!!!"

# 定义测试阶段
test_stages:
  stage: test
  script:
    - echo "I am job1"
    - echo "I am in test stage"

# 定义部署阶段
deploy_stages:
  stage: deploy
  script:
    - echo "I am job2"
    - echo "I am in build stage"
