# 定义 stages
stages:
  - build
  - test
  - deploy

variables:
  LS_CMD: 'ls $FLAGS $$TMP_DIR'
  FLAGS: '-al'
  FLAGST: 'echo $CI_RUNNER_ID'
  MY_CI_REGISTRY_IMAGE: '10.201.253.197:5000/'${CI_PROJECT_NAME}':'${$CI_BUILD_TAG}
  
# 定义编译阶段
build_stages:
  stage: build
  script:
#    - docker build -t developer/developer-base:1.01 . 
    - echo $CI_RUNNER_ID
    - echo $CI_BUILD_TAG
    - echo $RELEASE_IMAGE
    - export
    - if [ "$CI_BUILD_TAG" ]; then
        docker build -t $MY_CI_REGISTRY_IMAGE .;
      fi
 
# 定义测试阶段
test_stages:
  stage: test
  script:
    - echo "I am job1"
    - echo "I am in test stage"

# 定义部署阶段
deploy_stages:
  stage: deploy
  script:
    - echo "I am job2"
    - echo "I am in build stage"
