# 定义 stages
stages:
  - build
  - test
  - deploy
#  - apibuild

variables:
  LS_CMD: 'ls $FLAGS $$TMP_DIR'
  FLAGS: '-al'
  FLAGST: 'echo $CI_RUNNER_ID'
  MY_CI_REGISTRY_IMAGE: 117.187.12.236:15000/${CI_PROJECT_NAME}:$CI_BUILD_TAG
  MY_MARATHON_URL: 192.168.9.61:8080
# 定义编译阶段
build_stages:
  stage: build
  script:
#    - docker build -t developer/developer-base:1.01 . 
    - echo $CI_BUILD_TAG
    - echo $MY_CI_REGISTRY_IMAGE
    - export
    - docker
#    - docker build -t $TEST_CI_REGISTRY_IMAGE .
    - if [ "$CI_BUILD_TAG" ]; then  docker build -t $MY_CI_REGISTRY_IMAGE .;fi
    
#    - if [ -n "${PUSH_TO_REGISTRY}" ]; then docker build -t $MY_CI_REGISTRY_IMAGE .;fi
  tags:
    - dockerin
# 定义测试阶段
test_stages:
  tags:
    - dockerin
  stage: test
  script:
    - cd Code/develop-base/test
#    - code mocha
    - echo "TEST"
    - echo "test stage"

# 定义部署阶段
release_image:
  tags:
    - dockerin
  stage: deploy
  script:
    - ping 117.187.12.236
    - if [ "$CI_BUILD_TAG" ]; then docker push $MY_CI_REGISTRY_IMAGE ;fi
    - if [ "$CI_BUILD_TAG" ]; then  curl -X POST http://$MY_MARATHON_URL/v2/apps -d @architecture.json -H 'Content-type:application/json' ;fi
#    - if [ -n "${PUSH_TO_REGISTRY}" ]; then docker push $MY_CI_REGISTRY_IMAGE ;fi
    
    
#
# 定义部署阶段
#api_build:
#  tags:
#    - dev
#  stage: apibuild
#  before_script:
#    - if [ -n "${API_BUILD}" ]; then MY_CI_REGISTRY_IMAGE=192.168.31.92:5000/${CI_PROJECT_NAME}:${VERISON} ; fi
#  script:
#    - if [ -n "${API_BUILD}" ]; then docker build -t $MY_CI_REGISTRY_IMAGE .;fi
#    - if [ -n "${API_BUILD}" ]; then docker push $MY_CI_REGISTRY_IMAGE ;fi
    
